[fix] fix a compile error in opaque.c
when compiling with Ubuntu 20.04.1.

Before this commit, executing the following commands resulted in a compile
error:

```
$ docker run -it --rm --volume $(pwd):/tmp --workdir /tmp ubuntu:focal bash

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ apt update &&
apt-get install -y git build-essential &&
cd src &&
git submodule update --init --recursive tests/munit &&
apt-get install -y python libsodium-dev pkgconf &&
make bin libopaque.so tests/opaque
...
make: Nothing to be done for 'bin'.
gcc -march=native -Wall -fPIC -O2 -g -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fasynchronous-unwind-tables -fpic -fstack-clash-protection -fcf-protection=full -Werror=format-security -Werror=implicit-function-declaration -Wl,-z,defs -Wl,-z,relro -ftrapv -Wl,-z,noexecstack -DTRACE -DNORANDOM -Iaux -o common.o -c common.c
gcc -march=native -Wall -fPIC -O2 -g -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fasynchronous-unwind-tables -fpic -fstack-clash-protection -fcf-protection=full -Werror=format-security -Werror=implicit-function-declaration -Wl,-z,defs -Wl,-z,relro -ftrapv -Wl,-z,noexecstack -DTRACE -DNORANDOM -Iaux -o opaque.o -c opaque.c
opaque.c: In function 'opaque_Register':
opaque.c:829:73: error: 'Opaque_PkgConfig' {aka 'const struct <anonymous>'} has no member named 'sku'; did you mean 'skU'?
  829 |   fprintf(stderr, "cfg sku: %d, pku:%d, pks:%d, idu:%d, ids:%d\n", cfg->sku, cfg->pku, cfg->pks, cfg->idu, cfg->ids);
      |                                                                         ^~~
      |                                                                         skU
opaque.c:829:83: error: 'Opaque_PkgConfig' {aka 'const struct <anonymous>'} has no member named 'pku'; did you mean 'pkU'?
  829 |   fprintf(stderr, "cfg sku: %d, pku:%d, pks:%d, idu:%d, ids:%d\n", cfg->sku, cfg->pku, cfg->pks, cfg->idu, cfg->ids);
      |                                                                                   ^~~
      |                                                                                   pkU
opaque.c:829:93: error: 'Opaque_PkgConfig' {aka 'const struct <anonymous>'} has no member named 'pks'; did you mean 'pkU'?
  829 |   fprintf(stderr, "cfg sku: %d, pku:%d, pks:%d, idu:%d, ids:%d\n", cfg->sku, cfg->pku, cfg->pks, cfg->idu, cfg->ids);
      |                                                                                             ^~~
      |                                                                                             pkU
opaque.c:829:103: error: 'Opaque_PkgConfig' {aka 'const struct <anonymous>'} has no member named 'idu'; did you mean 'idU'?
  829 |   fprintf(stderr, "cfg sku: %d, pku:%d, pks:%d, idu:%d, ids:%d\n", cfg->sku, cfg->pku, cfg->pks, cfg->idu, cfg->ids);
      |                                                                                                       ^~~
      |                                                                                                       idU
opaque.c:829:113: error: 'Opaque_PkgConfig' {aka 'const struct <anonymous>'} has no member named 'ids'; did you mean 'idU'?
  829 |   fprintf(stderr, "cfg sku: %d, pku:%d, pks:%d, idu:%d, ids:%d\n", cfg->sku, cfg->pku, cfg->pks, cfg->idu, cfg->ids);
      |                                                                                                                 ^~~
      |                                                                                                                 idU
make: *** [makefile:41: opaque.o] Error 1
```

`Opaque_PkgConfig` is defined in `opaque.h`:
```
typedef struct {
  Opaque_PkgTarget skU : 2;  /**< users secret key - must not be
                                InClrEnv, if it is NotPackaged then
                                rwdU is used to seed a keygen() via
                                hkdf-expand() */
  Opaque_PkgTarget pkU : 2;  /**< users public key - if not included
                                it can be derived from the private
                                key */
  Opaque_PkgTarget pkS : 2;  /**< servers public key - currently this
                                is not allowed to set to NotPackaged -
                                TODO if set to NotPackaged allow to
                                specify the pubkey explicitly as a
                                param to the functions that require
                                this info */
  Opaque_PkgTarget idU : 2;  /**< id of the user - the RFC specifies
                                this to be possible to pack into the
                                envelope */
  Opaque_PkgTarget idS : 2;  /**< id of the server - the RFC specifies
                                this to be possible to pack into the
                                envelope */
} Opaque_PkgConfig;
```