[build] update runs-on attribute for codeql-analysis.yml
since ubuntu-latest, which currently is ubuntu-18.04, does not work:
```
make: Nothing to be done for 'bin'.
gcc -march=native -Wall -fPIC -O2 -g -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fasynchronous-unwind-tables -fpic -fstack-clash-protection -fcf-protection=full -Werror=format-security -Werror=implicit-function-declaration -Wl,-z,defs -Wl,-z,relro -ftrapv -Wl,-z,noexecstack -DTRACE -DNORANDOM -Iaux -o common.o -c common.c
gcc: error: unrecognized command line option ‘-fstack-clash-protection’; did you mean ‘-fstack-protector’?
gcc: error: unrecognized command line option ‘-fcf-protection=full’; did you mean ‘-fstack-protector-all’?
makefile:41: recipe for target 'common.o' failed
make: *** [common.o] Error 1
Error: Process completed with exit code 2.
```