[build] update build instructions and have the GitHub action run tests
not just build tests.

Python is not necessary to build the project. We appear to only use it for
src/tests/gencfg.py.

I also did the following:
- I removed libsodium from the build since it's installed as part of
  libsodium-dev:
```
root# apt-get install -y libsodium-dev pkgconf
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libpkgconf3 libsodium23
The following NEW packages will be installed:
  libpkgconf3 libsodium-dev libsodium23 pkgconf
```
- I alphabetized the install list: libsodium-dev pkgconf
- I removed bin from the make line. It does nothing:
```
root# make bin
make: Nothing to be done for 'bin'.
```
- I removed tests since test depends upon tests.
- I added test to the build so that the GitHub action runs tests.
- I updated `make test` to use `LD_LIBRARY_PATH=.` to prevent the following
  error as seen in https://github.com/creemama/libopaque/runs/1653874110.
```
LD_PRELOAD=./libopaque.so ./tests/munit-opaque --fatal-failures
./tests/munit-opaque: error while loading shared libraries: libopaque.so: cannot open shared object file: No such file or directory
make: *** [makefile:32: test] Error 127
Error: Process completed with exit code 2.
```

[fix]